# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"
    restart: always
    volumes: 
        - database-data:/var/lib/postgresql/data/

  pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin:

